version: "3.4"
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "sa12345678"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - './drive:/var/opt/mssql'
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sa12345678
      - POSTGRES_USER=sa
      - POSTGRES_DB=theMealAppDB
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672